name: IBM Cloud Auto Restart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 11 * * FRI'

jobs:
  ibm-cloud-restart:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init
      run: |
        chmod -R 777 ./IBM_Cloud_CLI/
    - name: Login IBM Cloud
      env:
        IBM_ACCOUNT_SYG: ${{ secrets.IBM_ACCOUNT_SYG }}
        REGION_NUM: ${{ secrets.REGION_NUM }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud login <<EOF
        $IBM_ACCOUNT_SYG
        $REGION_NUM
        no
        EOF
    - name: Target IBM Cloud
      env:
        RESOURSE_ID_QYDAB: ${{ secrets.RESOURSE_ID_QYDAB }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud target -g "$RESOURSE_ID_QYDAB"
        ./IBM_Cloud_CLI/ibmcloud target --cf
        ./IBM_Cloud_CLI/ibmcloud cf install -v 6.51.0
    - name: Restart IBM Cloud
      env:
        IBM_APP_NAME_QYDAB: ${{ secrets.IBM_APP_NAME_QYDAB }}
      run: |
        ./IBM_Cloud_CLI/ibmcloud cf restart "$IBM_APP_NAME_QYDAB"
